stages:
  - build
  - release


variables:
  # Commit tags regex to determine what pipeline to run
  RELEASE_TAG: '/^\d.\d.\d$/'
  # Name of the tag when doing manual builds
  CUSTOM_TAG: ''
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  # Image names
  PRIVATE_IMAGE: '$CI_REGISTRY/mcmanager/mcmanager'
  PUBLIC_IMAGE: '$DOCKERHUB_USER/mcmanager'


default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


# Development build - On new commits
dev:build:
  stage: build
  tags:
    - build
  script:
    # Build the image and upload to to the private registry
    - |
      docker build -t $PRIVATE_IMAGE:dev-$CI_COMMIT_SHORT_SHA . \
      --build-arg C_OPTIMIZATION="-Og" \
      --build-arg BUILD_TYPE="debug"
    - docker push $PRIVATE_IMAGE:dev-$CI_COMMIT_SHORT_SHA
    - docker tag $PRIVATE_IMAGE:dev-$CI_COMMIT_SHORT_SHA $PRIVATE_IMAGE:dev-latest
    - docker push $PRIVATE_IMAGE:dev-latest
  rules:
    # don't run this for release tags
    - if: $CI_COMMIT_TAG =~ $RELEASE_TAG
      when: never
    # run this at every push for the changed files
    - if: $CI_PIPELINE_SOURCE == "push"
      # and if we have changes in relevant files when pushing a new commit
      changes:
        - Dockerfile
        - Sources/**/*
        - Tests/**/*
        - Package.*
      when: always
    # build for merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always


# Release build - New tags matching RELEASE_TAG
release:build:
  stage: build
  tags:
    - build
  script:
    # Build and upload to private registry
    - docker build -t $PRIVATE_IMAGE:$CI_COMMIT_TAG .
    - docker push $PRIVATE_IMAGE:$CI_COMMIT_TAG
  rules:
    # run this when we have a release tag
    - if: $CI_COMMIT_TAG =~ $RELEASE_TAG


# Release - Upload the image to dockerhub
release:dockerhub:
  stage: release
  tags:
    - upload
  script:
    # Download the newly built image
    - docker pull $PRIVATE_IMAGE:$CI_COMMIT_TAG
    # Login into dockerhub
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
    # Tag the image as latest and push
    - docker tag $PRIVATE_IMAGE:$CI_COMMIT_TAG $PUBLIC_IMAGE:$CI_COMMIT_TAG
    - docker tag $PUBLIC_IMAGE:$CI_COMMIT_TAG $PUBLIC_IMAGE:latest
    - docker push $PUBLIC_IMAGE:$CI_COMMIT_TAG
    - docker push $PUBLIC_IMAGE:latest
  rules:
    - if: $CI_COMMIT_TAG =~ $RELEASE_TAG
      when: on_success


release:docs:
  stage: release
  tags:
    - upload
  image: alpine:latest
  script:
    - apk update && apk add curl
    - |
      curl --location \
      --output /usr/local/bin/release-cli \
      "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
    - chmod +x /usr/local/bin/release-cli
    - echo 'Creating release $CI_COMMIT_TAG'
  rules:
    - if: $CI_COMMIT_TAG =~ $RELEASE_TAG
      when: on_success
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    # TODO: Find a way to add a direct link to the image
    description: '[DockerHub - MCManager](https://hub.docker.com/repository/docker/rdall96/mcmanager/general)\n$IMAGE_NAME:$CI_COMMIT_TAG\nAutomated release (maintainer to fill in details)'


# Manual build - On custom build tags (for testing purposes)
manual:build:
  stage: build
  tags:
    - build
  script:
    # Build and push to the private registry
    - docker build -t $PRIVATE_IMAGE:$CUSTOM_TAG .
    - docker push $PRIVATE_IMAGE:$CUSTOM_TAG
  rules:
    # run this when a custom tag is created (optional)
    - if: $CUSTOM_TAG != null && $CUSTOM_TAG != ""
      when: manual
